apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: prana12/dwk-4-gitops-app
  newTag: e5353256453736d783c4ad1eac89c2921fa310a9
